using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using Glasswork.Core.Models;

namespace Glasswork.Core.Services;

/// <summary>
/// Auto-generates _index.md (full task manifest) and _today.md (My Day snapshot)
/// in the vault directory. These files are the agent-readable surfaces.
/// </summary>
public class IndexService
{
    private readonly VaultService _vault;

    public IndexService(VaultService vault)
    {
        _vault = vault;
    }

    /// <summary>
    /// Regenerate both _index.md and _today.md from the current task files.
    /// Call this after any task create/update/delete.
    /// </summary>
    public void Refresh()
    {
        var tasks = _vault.LoadAll();
        WriteIndex(tasks);
        WriteToday(tasks);
    }

    private void WriteIndex(List<GlassworkTask> tasks)
    {
        var sb = new StringBuilder();
        sb.AppendLine("---");
        sb.AppendLine("id: todo-index");
        sb.AppendLine("title: Glasswork Task Index");
        sb.AppendLine("type: index");
        sb.AppendLine($"updated: {DateTime.Today:yyyy-MM-dd}");
        sb.AppendLine("---");
        sb.AppendLine();
        sb.AppendLine("# Glasswork Tasks");
        sb.AppendLine();
        sb.AppendLine("> Auto-generated by Glasswork. Do not edit manually.");
        sb.AppendLine();

        // Group by status
        WriteStatusSection(sb, "In Progress", tasks.Where(t => t.Status == GlassworkTask.Statuses.InProgress));
        WriteStatusSection(sb, "Todo", tasks.Where(t => t.Status == GlassworkTask.Statuses.Todo));
        WriteStatusSection(sb, "Done (Recent)", tasks
            .Where(t => t.Status == GlassworkTask.Statuses.Done)
            .OrderByDescending(t => t.CompletedAt)
            .Take(20));

        File.WriteAllText(Path.Combine(_vault.VaultPath, "_index.md"), sb.ToString());
    }

    private void WriteToday(List<GlassworkTask> tasks)
    {
        var todayTasks = tasks.Where(t => t.IsMyDay).ToList();

        var sb = new StringBuilder();
        sb.AppendLine("---");
        sb.AppendLine("id: todo-today");
        sb.AppendLine("title: Glasswork — My Day");
        sb.AppendLine("type: index");
        sb.AppendLine($"updated: {DateTime.Today:yyyy-MM-dd}");
        sb.AppendLine("---");
        sb.AppendLine();
        sb.AppendLine("# My Day");
        sb.AppendLine();
        sb.AppendLine("> Auto-generated by Glasswork. Shows what TJ is focused on today.");
        sb.AppendLine();

        if (todayTasks.Count == 0)
        {
            sb.AppendLine("*No tasks picked for today yet.*");
        }
        else
        {
            sb.AppendLine("| Task | Priority | Status | ADO |");
            sb.AppendLine("|------|----------|--------|-----|");
            foreach (var t in todayTasks)
            {
                var ado = t.AdoLink.HasValue ? $"[#{t.AdoLink}] {t.AdoTitle ?? ""}" : "";
                sb.AppendLine($"| [[{t.Id}|{t.Title}]] | {t.Priority} | {t.Status} | {ado} |");
            }
        }

        sb.AppendLine();
        File.WriteAllText(Path.Combine(_vault.VaultPath, "_today.md"), sb.ToString());
    }

    private static void WriteStatusSection(StringBuilder sb, string heading, IEnumerable<GlassworkTask> tasks)
    {
        var list = tasks.ToList();
        if (list.Count == 0) return;

        sb.AppendLine($"## {heading}");
        sb.AppendLine();
        sb.AppendLine("| Task | Priority | ADO | Created |");
        sb.AppendLine("|------|----------|-----|---------|");
        foreach (var t in list)
        {
            var ado = t.AdoLink.HasValue ? $"[#{t.AdoLink}] {t.AdoTitle ?? ""}" : "";
            sb.AppendLine($"| [[{t.Id}|{t.Title}]] | {t.Priority} | {ado} | {t.Created:yyyy-MM-dd} |");
        }
        sb.AppendLine();
    }
}
